### ISSUE TITLE
Error: describe with no children (describe() or it())

### ISSUE THREAD

**Issue by grosswilerp** [lbovet/rulya#1]
When using the `skip` modifier in a YAML:

```
spec:
  chargeableUnit: "TODO" # skip(chargeableUnit)
```
and you write something like this:
```
    property("spec", application.spec, spec => {}
```
then the following error is being produced:
```
Suite error: 'XXX.yml'
  Message:
    Error: describe with no children (describe() or it())
  Stack:
        at <Jasmine>
        at property (node_modules/rulya/index.js:123:11)
        at validate.js:51:5
        at node_modules/rulya/index.js:64:13
        at <Jasmine>
        at node_modules/rulya/index.js:63:9
        at Array.forEach (<anonymous>)
```
I assume this happens due to the fact that Rulya is skipping that property and therefore this rule has no effect. Is there a way to fix this?

**Comment by lbovet** [comment]
https://www.npmjs.com/package/rulya/v/1.0.6
